documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/**'

reverse-proxy:
- changed-files:
  - any-glob-to-any-file: 'plugins/**'

provider:
- changed-files:
  - any-glob-to-any-file: 'app/providers/**'

ci:
- changed-files:
  - any-glob-to-any-file: '.github/**'